FROM python:3.12-alpine
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk add --no-cache \
    python3-dev \
    gcc \
    postgresql-dev \
    libffi-dev \
    libtool \
    build-base

RUN pip install --upgrade pip && \
    pip install pipx && \
    pipx install poetry

ENV PATH="/root/.local/bin:$PATH"

COPY ./pyproject.toml /app/
COPY ./poetry.lock /app/

RUN poetry install --no-dev --no-interaction --no-ansi

COPY . /app

COPY ./scripts /scripts
RUN chmod +x /scripts/*

RUN mkdir -p /vol/web/media
RUN mkdir -p /vol/web/static


CMD ["sh", "scripts/init.sh"]